.\" Manpage for fell - the furious shell
.\" Contact fried.ice.94@gmail.com for bugs or errors
.TH man 1 "22 April 2017" "0.1" "fell man page"
.SH NAME
fell \- The furious shell
.SH SYNOPSIS
fell
.SH DESCRIPTION
Fell is a simple shell created for understanding the linux way of creating new processes by forkinging and executing. It is not supposed to deliver every day usage shell experience.
.SH OPTIONS
As of now, there are no options available.
.SH SEE ALSO
fork (3), exex (3), waitpid (3)
.SH BUGS
Probably a lot.
.SH AUTHOR
Fried Ice (fried.ice.94@gmail.com)
