name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install build dependencies
      run: apt install pandoc
    - name: Create configure script
      run: ./prepare.sh
    - name: Configure project
      run: ./configure
    - name: compile
      run: make clean check -j2
